#encoding: utf-8
import  os

#数据库配置
HOSTMAME='127.0.0.1'
PORT='3306'
DATABASE='demo'
USERNAME='root'
PASSWORD='plmokn333'
DB_URI='mysql+pymysql://{}:{}@{}:{}/{}?charset=utf8'.format(USERNAME,PASSWORD,HOSTMAME,PORT,DATABASE)
SQLALCHEMY_DATABASE_URI=DB_URI

SQLALCHEMY_TRACK_MODIFICATIONS=True


SECRET_KEY ="21331213sdsfasf"