# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(450, 235)
        Dialog.setMinimumSize(QtCore.QSize(450, 235))
        Dialog.setMaximumSize(QtCore.QSize(450, 235))
        Dialog.setStyleSheet("QDialog {\n"
"    background:rgb(51,51,51);\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setStyleSheet("background:rgb(51,51,51);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_top = QtWidgets.QFrame(self.frame_2)
        self.frame_top.setMinimumSize(QtCore.QSize(0, 55))
        self.frame_top.setMaximumSize(QtCore.QSize(16777215, 55))
        self.frame_top.setStyleSheet("background:rgb(91,90,90);")
        self.frame_top.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_top)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lab_heading = QtWidgets.QLabel(self.frame_top)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.lab_heading.setFont(font)
        self.lab_heading.setStyleSheet("color:rgb(255,255,255);")
        self.lab_heading.setTextFormat(QtCore.Qt.AutoText)
        self.lab_heading.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lab_heading.setObjectName("lab_heading")
        self.horizontalLayout.addWidget(self.lab_heading)
        self.bn_min = QtWidgets.QPushButton(self.frame_top)
        self.bn_min.setMinimumSize(QtCore.QSize(55, 55))
        self.bn_min.setMaximumSize(QtCore.QSize(55, 55))
        self.bn_min.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(0,143,150);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(51,51,51);\n"
"}")
        self.bn_min.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/1x/hideAsset 53.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bn_min.setIcon(icon)
        self.bn_min.setIconSize(QtCore.QSize(22, 12))
        self.bn_min.setAutoDefault(False)
        self.bn_min.setFlat(True)
        self.bn_min.setObjectName("bn_min")
        self.horizontalLayout.addWidget(self.bn_min)
        self.bn_close = QtWidgets.QPushButton(self.frame_top)
        self.bn_close.setMinimumSize(QtCore.QSize(55, 55))
        self.bn_close.setMaximumSize(QtCore.QSize(55, 55))
        self.bn_close.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(0,143,150);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(51,51,51);\n"
"}")
        self.bn_close.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/1x/closeAsset 43.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bn_close.setIcon(icon1)
        self.bn_close.setIconSize(QtCore.QSize(22, 22))
        self.bn_close.setAutoDefault(False)
        self.bn_close.setFlat(True)
        self.bn_close.setObjectName("bn_close")
        self.horizontalLayout.addWidget(self.bn_close)
        self.verticalLayout_2.addWidget(self.frame_top)
        self.frame_bottom = QtWidgets.QFrame(self.frame_2)
        self.frame_bottom.setStyleSheet("background:rgb(91,90,90);")
        self.frame_bottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_bottom.setObjectName("frame_bottom")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_bottom)
        self.gridLayout.setObjectName("gridLayout")
        self.password = QtWidgets.QLabel(self.frame_bottom)
        self.password.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.password.setFont(font)
        self.password.setStyleSheet("color:rgb(255,255,255);")
        self.password.setObjectName("password")
        self.gridLayout.addWidget(self.password, 2, 0, 1, 2)
        self.bt1 = QtWidgets.QPushButton(self.frame_bottom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt1.sizePolicy().hasHeightForWidth())
        self.bt1.setSizePolicy(sizePolicy)
        self.bt1.setMinimumSize(QtCore.QSize(69, 40))
        self.bt1.setMaximumSize(QtCore.QSize(69, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.bt1.setFont(font)
        self.bt1.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    border-radius: 5px;    \n"
"    color:rgb(255,255,255);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: rgb(0,143,150);\n"
"}\n"
"QPushButton:pressed {    \n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: rgb(51,51,51);\n"
"}")
        self.bt1.setAutoDefault(False)
        self.bt1.setObjectName("bt1")
        self.gridLayout.addWidget(self.bt1, 4, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 70, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 1)
        self.lab_icon = QtWidgets.QLabel(self.frame_bottom)
        self.lab_icon.setMinimumSize(QtCore.QSize(40, 40))
        self.lab_icon.setMaximumSize(QtCore.QSize(40, 40))
        self.lab_icon.setText("")
        self.lab_icon.setObjectName("lab_icon")
        self.gridLayout.addWidget(self.lab_icon, 1, 1, 1, 1)
        self.name_2 = QtWidgets.QLabel(self.frame_bottom)
        self.name_2.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.name_2.setFont(font)
        self.name_2.setStyleSheet("color:rgb(255,255,255);")
        self.name_2.setObjectName("name_2")
        self.gridLayout.addWidget(self.name_2, 0, 0, 2, 2)
        self.passwd = QtWidgets.QLineEdit(self.frame_bottom)
        self.passwd.setEnabled(True)
        self.passwd.setMinimumSize(QtCore.QSize(300, 25))
        self.passwd.setMaximumSize(QtCore.QSize(400, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.passwd.setFont(font)
        self.passwd.setStyleSheet("QLineEdit {\n"
"    color:rgb(255,255,255);\n"
"    border:2px solid rgb(51,51,51);\n"
"    border-radius:4px;\n"
"    background:rgb(51,51,51);\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    color:rgb(255,255,255);\n"
"    border:2px solid rgb(112,112,112);\n"
"    border-radius:4px;\n"
"    background:rgb(112,112,112);\n"
"}")
        self.passwd.setText("")
        self.passwd.setObjectName("passwd")
        self.gridLayout.addWidget(self.passwd, 2, 2, 1, 2)
        self.bt2 = QtWidgets.QPushButton(self.frame_bottom)
        self.bt2.setMinimumSize(QtCore.QSize(69, 40))
        self.bt2.setMaximumSize(QtCore.QSize(69, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.bt2.setFont(font)
        self.bt2.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    border-radius: 5px;    \n"
"    color:rgb(255,255,255);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: rgb(0,143,150);\n"
"}\n"
"QPushButton:pressed {    \n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: rgb(51,51,51);\n"
"}")
        self.bt2.setAutoDefault(False)
        self.bt2.setObjectName("bt2")
        self.gridLayout.addWidget(self.bt2, 4, 3, 1, 1)
        self.name = QtWidgets.QLineEdit(self.frame_bottom)
        self.name.setEnabled(True)
        self.name.setMinimumSize(QtCore.QSize(300, 25))
        self.name.setMaximumSize(QtCore.QSize(400, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.name.setFont(font)
        self.name.setStyleSheet("QLineEdit {\n"
"    color:rgb(255,255,255);\n"
"    border:2px solid rgb(51,51,51);\n"
"    border-radius:4px;\n"
"    background:rgb(51,51,51);\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    color:rgb(255,255,255);\n"
"    border:2px solid rgb(112,112,112);\n"
"    border-radius:4px;\n"
"    background:rgb(112,112,112);\n"
"}")
        self.name.setText("")
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 0, 2, 2, 2)
        self.bt2.raise_()
        self.lab_icon.raise_()
        self.name_2.raise_()
        self.password.raise_()
        self.bt1.raise_()
        self.passwd.raise_()
        self.name.raise_()
        self.verticalLayout_2.addWidget(self.frame_bottom)
        self.verticalLayout.addWidget(self.frame_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.name, self.passwd)
        Dialog.setTabOrder(self.passwd, self.bt1)
        Dialog.setTabOrder(self.bt1, self.bt2)
        Dialog.setTabOrder(self.bt2, self.bn_min)
        Dialog.setTabOrder(self.bn_min, self.bn_close)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lab_heading.setText(_translate("Dialog", "登录"))
        self.password.setText(_translate("Dialog", "密码："))
        self.bt1.setText(_translate("Dialog", "登录"))
        self.name_2.setText(_translate("Dialog", "用户名："))
        self.bt2.setText(_translate("Dialog", "取消"))
