"""empty message

Revision ID: 3ad10b318012
Revises: a555fd2c2843
Create Date: 2022-07-01 22:55:00.895317

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3ad10b318012'
down_revision = 'a555fd2c2843'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_data', sa.Column('create_time', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_data', 'create_time')
    # ### end Alembic commands ###
