"""empty message

Revision ID: 476a9ce6c9ec
Revises: 67ab5279dfcd
Create Date: 2022-07-01 17:11:49.597053

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '476a9ce6c9ec'
down_revision = '67ab5279dfcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('phonenumber', table_name='user_test')
    op.drop_index('username', table_name='user_test')
    op.drop_table('user_test')
    op.add_column('user_data', sa.Column('password', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=20), nullable=False, comment='用户登录密码'))
    op.add_column('user_data', sa.Column('vip_level', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='vip等级'))
    op.drop_index('name', table_name='user_data')
    op.drop_column('user_data', 'avatar')
    op.drop_column('user_data', 'viplevel')
    op.drop_column('user_data', 'passwd')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_data', sa.Column('passwd', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=20), nullable=False, comment='用户登录密码'))
    op.add_column('user_data', sa.Column('viplevel', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='vip等级'))
    op.add_column('user_data', sa.Column('avatar', mysql.MEDIUMBLOB(), nullable=True, comment='用户头像'))
    op.create_index('name', 'user_data', ['name'], unique=False)
    op.drop_column('user_data', 'vip_level')
    op.drop_column('user_data', 'password')
    op.create_table('user_test',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('nickname', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('phonenumber', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'user_test', ['username'], unique=False)
    op.create_index('phonenumber', 'user_test', ['phonenumber'], unique=False)
    op.drop_table('question_data')
    # ### end Alembic commands ###
