"""empty message

Revision ID: 61003e27fd95
Revises: 476a9ce6c9ec
Create Date: 2022-07-01 17:15:43.090481

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '61003e27fd95'
down_revision = '476a9ce6c9ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('phonenumber', table_name='user_test')
    op.drop_index('username', table_name='user_test')
    op.drop_table('user_test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_test',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('nickname', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('phonenumber', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'user_test', ['username'], unique=False)
    op.create_index('phonenumber', 'user_test', ['phonenumber'], unique=False)
    op.drop_table('question_data')
    # ### end Alembic commands ###
