"""empty message

Revision ID: 67ab5279dfcd
Revises: c74d64cbbb99
Create Date: 2022-07-01 15:46:43.964168

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '67ab5279dfcd'
down_revision = 'c74d64cbbb99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('phonenumber', table_name='user_test')
    op.drop_index('username', table_name='user_test')
    op.drop_table('user_test')
    op.add_column('user_data', sa.Column('username', sa.String(length=200), nullable=False))
    op.add_column('user_data', sa.Column('password', sa.String(length=200), nullable=False))
    op.alter_column('user_data', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='用户id，唯一标识',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_data', 'nickname',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=30),
               nullable=False,
               comment=None,
               existing_comment='用户昵称，可重名')
    op.alter_column('user_data', 'phonenumber',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=11),
               nullable=False,
               comment=None,
               existing_comment='用户手机号码')
    op.alter_column('user_data', 'create_time',
               existing_type=mysql.TIMESTAMP(),
               comment=None,
               existing_comment='用户创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('name', table_name='user_data')
    op.create_unique_constraint(None, 'user_data', ['phonenumber'])
    op.create_unique_constraint(None, 'user_data', ['username'])
    op.drop_column('user_data', 'gender')
    op.drop_column('user_data', 'viplevel')
    op.drop_column('user_data', 'passwd')
    op.drop_column('user_data', 'name')
    op.drop_column('user_data', 'balance')
    op.drop_column('user_data', 'avatar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_data', sa.Column('avatar', mysql.MEDIUMBLOB(), nullable=True, comment='用户头像'))
    op.add_column('user_data', sa.Column('balance', mysql.INTEGER(unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='账户余额，单位为人民币'))
    op.add_column('user_data', sa.Column('name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=30), nullable=False, comment='用户名'))
    op.add_column('user_data', sa.Column('passwd', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=20), nullable=False, comment='用户登录密码'))
    op.add_column('user_data', sa.Column('viplevel', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='vip等级'))
    op.add_column('user_data', sa.Column('gender', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=6), nullable=True, comment='用户性别'))
    op.drop_constraint(None, 'user_data', type_='unique')
    op.drop_constraint(None, 'user_data', type_='unique')
    op.create_index('name', 'user_data', ['name'], unique=False)
    op.alter_column('user_data', 'create_time',
               existing_type=mysql.TIMESTAMP(),
               comment='用户创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user_data', 'phonenumber',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=11),
               nullable=True,
               comment='用户手机号码')
    op.alter_column('user_data', 'nickname',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=30),
               nullable=True,
               comment='用户昵称，可重名')
    op.alter_column('user_data', 'id',
               existing_type=mysql.INTEGER(),
               comment='用户id，唯一标识',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('user_data', 'password')
    op.drop_column('user_data', 'username')
    op.create_table('user_test',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('nickname', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('phonenumber', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'user_test', ['username'], unique=False)
    op.create_index('phonenumber', 'user_test', ['phonenumber'], unique=False)
    # ### end Alembic commands ###
