"""empty message

Revision ID: a555fd2c2843
Revises: 61003e27fd95
Create Date: 2022-07-01 22:14:21.738477

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a555fd2c2843'
down_revision = '61003e27fd95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_data', sa.Column('author_id', mysql.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'question_data', 'user_data', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question_data', type_='foreignkey')
    op.drop_column('question_data', 'author_id')
    # ### end Alembic commands ###
