"""empty message

Revision ID: d13a29b1ef7d
Revises: 3ad10b318012
Create Date: 2022-07-01 23:40:53.546470

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd13a29b1ef7d'
down_revision = '3ad10b318012'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_time', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('question_id', sa.INTEGER(), nullable=True),
    sa.Column('author_id', mysql.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user_data.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer_data')
    # ### end Alembic commands ###
